resolver: lts-17.0
compiler: ghc-8.10.2

packages:
  - .
extra-deps:
  - text-format-0.3.2
  - Diff-0.3.4
  - liquid-fixpoint-0.8.10.2
  - liquidhaskell-0.8.10.2
  - liquid-base-4.14.1.0
  - liquid-ghc-prim-0.6.1
  - liquid-containers-0.6.2.1 
